### ISSUE TITLE
gRPC with REST README typo

### ISSUE THREAD

**Issue by Enviy** [jannden/golang-examples#1]
In the [README for gRPC with REST](https://github.com/jannden/golang-examples/tree/main/grpc-with-rest), there's an example service call for REST and gRPC but they're titles are switched.

It looks like bullet three, the gRPC call should use the grpcurl tool instead of cURL and bullet four, the REST call, should use cURL.

**Comment by jannden** [comment]
Nice catch, thank you. It's fixed now.
